name: Terraform Deploy

on:
  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    defaults:
      run:
        working-directory: terraform/environments/dev

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::520900723145:role/github-actions-terraform-role
          aws-region: eu-west-2
      - name: Verify AWS identity and Route53
        run: |
          aws sts get-caller-identity
          aws route53 list-hosted-zones-by-name \
            --dns-name ecscloudsupport.com \
            --query "HostedZones[0].[Id,Name]" \
            --output text
            
      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan